- name: nginx install and run
  hosts: 172.31.80.180
  # hosts: all
  become: yes #take sudo access
  serial: 3
  tasks:
  - name: install nginx
    ansible.builtin.package: #heterogenous module that can work for all distributions
      name: nginx
      state: present

  - name: run nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes